<?php

declare(strict_types=1);

return [
    /*
    |--------------------------------------------------------------------------
    | Lescopr SDK Configuration
    |--------------------------------------------------------------------------
    |
    | These values are typically read from .lescopr.json (generated by
    | `lescopr init`). You may also set them here or via environment variables.
    |
    */

    'sdk_key'     => env('LESCOPR_SDK_KEY'),
    'api_key'     => env('LESCOPR_API_KEY'),
    'environment' => env('LESCOPR_ENVIRONMENT', env('APP_ENV', 'development')),

    /*
    |--------------------------------------------------------------------------
    | Auto-inject Monolog Handler
    |--------------------------------------------------------------------------
    | When true, the SDK will automatically inject a Monolog handler into
    | Laravel's default logging channel on boot.
    */
    'auto_inject_handler' => env('LESCOPR_AUTO_INJECT', true),

    /*
    |--------------------------------------------------------------------------
    | Debug Mode
    |--------------------------------------------------------------------------
    | Enables verbose internal logging to .lescopr.log.
    */
    'debug' => env('LESCOPR_DEBUG', false),
];

