name: Lescopr | PHP

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.2', '8.3']

    name: PHP ${{ matrix.php-version }} Test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, json
          coverage: none

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run tests (PHPUnit)
        run: composer test

  # --- Créer une Release GitHub ---
  create-release:
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
      - name: Checkout | code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
            persist-credentials: true
      
      - name: Setup | Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'   
      
      - name: Install | conventional-changelog-cli
        run: npm install -g conventional-changelog-cli    

      - name: Generate | Changelog
        run: conventional-changelog -p angular -i CHANGELOG.md -s -o CHANGELOG.md --commit-path . || echo "Changelog generation failed or file does not exist yet, continuing..."
    
      - name: Checkout main branch
        run: git checkout main

      - name: Commit | updated CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: updateCHANGELOG.mdForRelease ${{ github.ref_name }} :rocket:" 
          file_pattern: CHANGELOG.md
          branch: main
        
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          generate_release_notes: true
          draft: false
          prerelease: false

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
